### ISSUE TITLE
Optimize rendering output

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/fela#13]
Sharing static style declarations with all Selector variations could drastically reduce the markup size and improve performance. It would remove redundant styles in favor of reusing them.
e.g.
```javascript
const selector = props => ({
  color: props.color,
  fontSize: '12px',
  width: '20px',
  justifyContent: 'center',
  flexWrap: 'nowrap'
})

renderer.render(selector, { props: 'red' }) // => class1
renderer.render(selector, { props: 'blue' }) // => class2
```
produces the following CSS markup
```CSS
.class1 {
  color: red;
  font-size: 12px;
  width: 20px;
  justify-content: center;
  flex-wrap: nowrap
}

.class2 {
  color: blue;
  font-size: 12px;
  width: 20px;
  justify-content: center;
  flex-wrap: nowrap
}
```

we could optimize the rendering process to have the following markup:
```javascript
renderer.render(selector, { props: 'red' }) // => class1 class1-dyn1
renderer.render(selector, { props: 'blue' }) // => class1 class1-dyn2
```
```CSS
.class1 {
  font-size: 12px;
  width: 20px;
  justify-content: center;
  flex-wrap: nowrap
}

.class1-dyn1 {
  color: 'red'
}

.class1-dyn2 {
  color: 'blue'
}
```
