### ISSUE TITLE
Classname conflict with filterClassName

### ISSUE THREAD

**Issue by HugoGiraudel** [rofrischmann/fela#345]
**Version**: 3.0.5
**Environment**: Both
**Type**: Bug

-------------------
#### Description

Given:

```js
filterClassName: className => className !== 'ad'
```

We get:

```css
…
.ab{border:1px solid rgba(0, 0, 0, 0.1)}
.ac{background-color:rgb(255, 255, 255)}
.bd{border-bottom:0}
.ae{border-radius:4px 4px 0 0}
…
.ba{border-bottom-width:2px}
.bb{border-bottom-style:solid}
.bc{border-left-color:rgb(59, 208, 214)}
.bd{border-left-width:2px}
.be{border-left-style:solid}
…
```

For some reason, when we do `i + 1` because `.ad` should not be generated, it generates `.bd` (instead of `.ae`). And then, `.bd` gets generated twice with different styles.
