### ISSUE TITLE
Discussion: Load .css into a Fela component?

### ISSUE THREAD

**Issue by alanhogan** [rofrischmann/fela#383]
This isn’t a Fela core feature request.

I am wondering if anyone has attempted to build a loader that could consume a .css file, or less directly, a .css file that has been loaded with CSS Modules, and generate a function that takes props and outputs style for Fela.

E.g., if you have this CSS file:

```css
.btn {
  border: 1px solid gray;
}

.btn.primary {
  background: blue;
  border-color-blue;
}

.btn-group {
  display: inline-block;
}
```

then you could do something like this:

```js
import css from "./btn.css";
import cssToFela from "css-to-fela"; // doesn't exist yet
import { createComponent } from "react-fela";

const btnStyles = cssToFela(css, '.btn');
const Button = createComponent(btnStyles, "button");
```

And then you could automatically gain the ability to get `primary` styles just by setting the `primary` prop when you use `Button`. You can consume styles from outside your own codebase and still gain the benefits of Fela's atomic compilation and all the other CSS-in-JS benefits.

Oh, and what happened to `.btn-group` above? Nothing. We only wanted the `.btn` styles when we imported the `.css` file, as we specified when invoking `cssToFela`.

Does anyone have any thoughts here?
