### ISSUE TITLE
fela-monolithic outputs classes twice

### ISSUE THREAD

**Issue by vlad-zhukov** [rofrischmann/fela#395]
**Version**: 6.0.x
**Environment**: Both
**Type**: Bug

-------------------
#### Description
Since 6.0 `fela-monolithic` enhancer outputs styles twice when generating with `renderToString` function from `fela-tools` (haven't tried other ways).

Without `fela-monolithic` I get the following:
```css
.a {
  color: red
}
```
But when I add it I get
```css
.rule_Loading__137u7ef {
  color: red
}
.rule_Loading__137u7ef {
  color: red
}
```

If there are more rules it will be like this:
```css
.rule_Loading__137u7ef {
  color: red
}
.rule_Loading__137u7ef:hover {
  color: yellow
}
.rule_Loading__137u7ef {
  color: red
}
.rule_Loading__137u7ef:hover {
  color: yellow
}
```

#### Steps to reproduce
Haven't reproduced it in a test environment yet.
