### ISSUE TITLE
fela-plugin-prefixer

### ISSUE THREAD

**Issue by vlad-zhukov** [rofrischmann/fela#406]
**Version**: 6.0.x
**Environment**: Both
**Type**: Bug

-------------------
#### Description
`fela-plugin-prefixer` incorrectly resolves the `display: flex` rule.

#### Expected Behavior
```css
.a {
  display: -webkit-box;
  display: -moz-box;
  display: -ms-flexbox;
  display: -webkit-flex;
  display: flex;
}
```

#### Actual Behavior
```css
.a {
  display: -webkit-box, -moz-box, -ms-flexbox, -webkit-flex, flex;
}
```

This happens because `inline-style-prefixer` returns styles like `display: ['-webkit-box', '-moz-box', '-ms-flexbox', '-webkit-flex', 'flex']`, but `css-in-js-utils/cssifyObjects` doesn't work with arrays and simply stringifies it into `'-webkit-box, -moz-box, -ms-flexbox, -webkit-flex, flex'`.
