### ISSUE TITLE
Issue when using fela-plugin-embedded `fontFace` using multiple fonts with same `familyName`

### ISSUE THREAD

**Issue by Cowboy-coder** [rofrischmann/fela#448]
**Version**: 6.0.x
**Environment**: Both
**Type**: Bug

-------------------
#### Description
I expect 
```js
const rule = () => ({
  fontFace: [
    {
      fontFamily: 'Arial',
      src: ['arial-regular.svg', 'arial-regular.ttf'],
      fontWeight: 400
    },
    {
      fontFamily: 'Arial',
      src: ['arial-bold.svg', 'arial-bold.ttf'],
      fontWeight: 700
    }
  ]
})
```
to render 
```css
@font-face{
  font-weight:400;
  src:url('arial-regular.svg') format('svg'),url('arial-regular.ttf') format('truetype');
  font-family:\"Arial\"
}
@font-face{
  font-weight:700;
  src:url('arial-bold.svg') format('svg'),url('arial-bold.ttf') format('truetype');
  font-family:\"Arial\"
}
```
and on the element:
```css
.a {
  font-family:"Arial"
}
```
but instead I get 
```css
.a {
  font-family:"Arial", "Arial"
}
```
on the element.

#### Steps to reproduce
1. First step
2. Second step

#### Proposal

I haven't digged into how to solve this or even if this should be solved like this, but I think it makes sense?

In any case, I have reproduced the error in a test-case:
```js
it('should render inline fonts with same fontFamily', () => {
  const rule = () => ({
    color: 'red',
    fontFace: [
      {
        fontFamily: 'Arial',
        src: ['arial-regular.svg', 'arial-regular.ttf'],
        fontWeight: 400
      },
      {
        fontFamily: 'Arial',
        src: ['arial-bold.svg', 'arial-bold.ttf'],
        fontWeight: 700
      }
    ]
  })

  const renderer = createRenderer({
    plugins: [embedded()]
  })
  renderer.renderRule(rule)

  expect(renderToString(renderer)).toEqual(
    "@font-face{font-weight:400;src:url('arial-regular.svg') format('svg'),url('arial-regular.ttf') format('truetype');font-family:\"Arial\"}@font-face{font-weight:700;src:url('arial-bold.svg') format('svg'),url('arial-bold.ttf') format('truetype');font-family:\"Arial\"}" +
      '.a{color:red}.c{font-family:"Arial"}'
  )
})
```
inside of `fela-plugin-embedded`.

**EDIT:**

One extra feature which I think makes sense is to be able to override the `familyName` as well:
```js
{
  fontFace: [
    {
      fontFamily: 'Arial',
      src: ['arial-regular.svg', 'arial-regular.ttf'],
      fontWeight: 400
    },
    {
      fontFamily: 'Arial',
      src: ['arial-bold.svg', 'arial-bold.ttf'],
      fontWeight: 700
    }
  ],
  fontFamily: 'Arial, sans-serif',
}
```
should generate `fontFamily: 'Arial, sans-serif'` on the element. Right now it becomes `Arial` (or `Arial, Arial` with this bug).
