### ISSUE TITLE
Does not render multiple static styles for a single selector

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/fela#56]
**Version**: 1.0.1
**Environment**: Both
**Type**: Bug

-------------------
#### Description
Please try to add as much detail as possible.

#### Steps to reproduce
```javascript
const renderer = createRenderer()

renderer.renderStatic({ color: 'red' }, 'div')
renderer.renderStatic({ fontSize: '12px' }, 'div')
```

#### Expected Behavior
Expected CSS output:
```CSS
div {
  color: red
}

div {
  font-size: 12px
}
```

#### Actual Behavior
Actual CSS output:
```CSS
div {
  color: red
}
```

#### Proposal
Not only use the selector as a cache reference, but the whole stringified style.
