### ISSUE TITLE
fela-plugin-unit adds 'px' at the end of unitless css variables

### ISSUE THREAD

**Issue by alanuecker** [rofrischmann/fela#606]
**Type**: Bug

| Packages | Version |
| -------- | ------- |
| fela     | 6.2.1   |
| fela-plugin-unit     | 5.1.0   |

-------------------
#### Description
The `unit` plugin will always add `px` at the end of the value since the key can not be checked for the unitless properties. 

##### Example
``` javascript
  const theme = {
    '--theme-z-index-modal': 1000,
    '--theme-z-index-snackbar': 1001,
  };

  renderer.renderStatic(theme, ':root');
```

##### Expected Behavior
```css
  :root {
    --theme-z-index-modal: 1000;
    --theme-z-index-snackbar: 1001;
  }
```

##### Actual Behavior
```css
  :root {
    --theme-z-index-modal: 1000px;
    --theme-z-index-snackbar: 1001px;
  }
```

#### Possible Solution
Maybe [isUnitlessProperty](https://github.com/rofrischmann/css-in-js-utils/blob/bf8576c09104afc2120b15208670237da58fb4f7/modules/isUnitlessProperty.js#L66-L68) should be extended to exclude css variables by default or via a prop. 

``` javascript
export default function isUnitlessProperty(property: string): boolean {
  return property.startsWith('--') || unitlessProperties.hasOwnProperty(property)
}
```
