### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/fela#70]
There should be an easy way to do theming.

We could use an enhancer to add a theme as second parameter of each rendering method.
Yet one could also theme using the props or a simple Theme singleton as well.

### Theming Enhancer
```javascript
const theme = { 
  PRIMARY: 'red', 
  SECONDARY: 'blue' 
}

const renderer = createRenderer({
  enhancers: [ theming(theme) ]
})

const rule = (props, theme) => ({
  fontSize: props.fontSize,
  color: props.color || theme.PRIMARY,
  backgroundColor: theme.SECONDARY
})

renderer.renderRule(rule, { fontSize: '15px' }) // => 'c0 c0-foo'
renderer.renderRule(rule, { fontSize: '20px', color: 'green' }) // => 'c0 c0-bar'
```
```CSS
.c0 {
  color: red;
  background-color: blue
}

.c0-foo {
  font-size: 15px
}

.c0-bar {
  font-size: 20px;
  color: green;
}
```

#### Base Styles
```javascript
const theme = { 
  PRIMARY: 'red', 
  SECONDARY: 'blue' ,
  styles: {
    button: { 
      color: 'blue', 
      lineHeight: '20px', 
      padding: '10px' 
    }
  }
}

const rule = (props, theme) => ({
  ...theme.styles.button,
  fontSize: props.fontSize,
  backgroundColor: theme.SECONDARY
})
```
