### ISSUE TITLE
Add option to make generated classnames even more helpful

### ISSUE THREAD

**Issue by maxharris9** [rofrischmann/fela#98]
#### Proposal

Make Fela emit even more human-readable classnames when `prettySelectors` option is enabled.

**Code Example**:

``` CSS
.heading_6 {
  padding-top: 25px;
  padding-bottom: 5px;
  font-weight: 600;
  letter-spacing: 1.9px;
  text-transform: uppercase;
  font-size: 0.75rem;
  color: #e1e7e6
}

.heading_6--njxhv5 {
  color: #89a19d
}
```

It would be nice if there were an option to make Fela emit something like `.heading_6--#89a19d` instead of `.heading_6--njxhv5`.

EDIT: Another related issue:

```
const margins = props => ({
  paddingLeft: '40px',
  paddingRight: '40px',
  '::-webkit-scrollbar': {
    display: 'none'
  }
})

export const Margins = createComponent(margins, 'div')

const scroll = props => ({
  overflow: 'scroll',
  height: props.useFullHeight ? '100vh' : null
})

export const Scroll = createComponent(scroll, 'div')

const marginsScroll = combineRules(margins, scroll)

export const MarginsScroll = createComponent(marginsScroll, 'div')
```

When `MarginsScroll` gets rendered, instead of a classname like `margins_scroll_14 margins_scroll_14-kd38uj`, we get back `c14 c14-kd38uj`.
